# Generated by Django 4.2.16 on 2024-09-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='price',
        ),
    ]
